### ISSUE TITLE
Python interface to Bifrost

### ISSUE THREAD

**Issue by winni2k** [pmelsted/bifrost#10]
Hi,
I would like to add Bifrost as a CDBG storage format/engine for [`cortexpy`](https://github.com/winni2k/cortexpy). I will need a cpython interface for that. I see in https://github.com/pmelsted/bifrost/issues/3#issuecomment-562127927 that there might already be some work done on such an interface. Any chance I could get access to that work to avoid reinventing the wheel? 

I would, of course, contribute any additions I make to that interface back to the original project.

Cheers,
Winni

**Comment by GuillaumeHolley** [comment]
Hi there,

Sorry for the delay. This sounds like a really nice project :) I can give you access to what has been done so far for our Python interface (using pybind11). Full warning: the python code hasn't changed for the past 18 months while the C++ code of Bifrost has changed quite a bit since then. Let me know if you still want to have a look. Thanks for your interest!

Best,
Guillaume

**Comment by winni2k** [comment]
That would be great! Do you have a repo or branch that I could pull?

I expect that my progress will be slow as I will be working on this part time, but perhaps I can push things along a bit.

**Comment by GuillaumeHolley** [comment]
Sorry again it took so long, I am myself working part time on this and I have been crazy busy those days. Anyway, I just send you an invite to contribute to `pybifrost`. For any questions or suggestions, you can contact me privately or maybe open an issue on the corresponding repo ;)

I am closing this issue.

Best,
Guillaume

**Comment by lrvdijk** [comment]
Hi @GuillaumeHolley and @winni2k,

I'd be interested in the Python interface too, and we also have some resources the coming year to contribute to the project. Let me know how I can help!

**Comment by GuillaumeHolley** [comment]
Hi @lrvdijk 

I just sent you an invite to our repo ;) All contributions are welcome. Thanks.

Guillaume

**Comment by lrvdijk** [comment]
Hi all (@GuillaumeHolley @winni2k),

I've started a new repository where I'm working on a Python interface with a NetworkX compatible API. It's in its very early stages, but some basic iteration and traversal functions are working. 

https://github.com/broadinstitute/pyfrost

**Comment by winni2k** [comment]
That's amazing! I'll have a look @lrvdijk

**Comment by GuillaumeHolley** [comment]
Hi guys,

It is a wonderful work @lrvdijk, thank you! I will keep a close eye on this project and it goes without saying that if you need anything, you let me know.

**Comment by GuillaumeHolley** [comment]
Hey @lrvdijk and @winni2k,

I started writing a tutorial for the Bifrost C++ API which is available [here](https://github.com/pmelsted/bifrost/blob/master/doc/tutorial/Intro.md). It is a work in progress, not much content for now but I intend to enhance it with a lot more in the coming weeks. I thought this might be helpful in your quest for a Python interface ;)

**Comment by winni2k** [comment]
Thanks for the heads-up!

**Comment by lrvdijk** [comment]
Nice, I've made quite a bit of progress on the Python interface, will put up some documentation soon

**Comment by lrvdijk** [comment]
A pre-pre-pre release of the Python interface can be here @winni2k @GuillaumeHolley : https://github.com/broadinstitute/pyfrost

**Comment by GuillaumeHolley** [comment]
Wow, amazing work @lrvdijk ! Unfortunately, I have little time to do Bifrost-related work at the moment but as soon as I have some time, I will give it a shot. Thanks!

**Comment by GuillaumeHolley** [comment]
Btw @lrvdijk, can I advertise your work "publicly" (i.e Twitter)?

**Comment by lrvdijk** [comment]
Thanks! Let's hold off for maybe a month before more broadly announcing it, in the coming weeks I'll use the library for some of my own research projects, and I'm sure I will encounter bugs and missing features. 

Will update when I'm more comfortable announcing it haha!

**Comment by winni2k** [comment]
This looks great! I have some thoughts/suggestions. I'll post those on the pyfrost repo.
