### ISSUE TITLE
Wrong GFA header error

### ISSUE THREAD

**Issue by Roger-BP** [pmelsted/bifrost#12]
Hi,

I've just recently discovered Bifrost and it sounds like a great tool for fast homology search as evidenced by the paper presenting BlastFrost. I'd love to start using both, however, I'm running into an issue when trying to build a Bifrost graph from several assembly graphs.

This is the exact command that I'm using:
./Bifrost build -c -v -r ${DATADIR}/isolate_graph_list.txt -o ${OUTDIR}/Bifrost_graph1

The error message is as follows:

KmerStream::KmerStream(): Start computing k-mer cardinality estimations
GFA_Parser::open(): Wrong GFA header in ~/data/graph_files/genome1.contigs.gfa
CompactedDBG::build(): Estimated number of k-mers occurring at least once: 1
CompactedDBG::build(): Estimated number of minimizer occurring at least once: 1
GFA_Parser::open(): Wrong GFA header in ~/data/graph_files/genome1.contigs.gfa
CompactedDBG::filter(): Closed all fasta/fastq files
CompactedDBG::filter(): Processed 0 k-mers in 0 reads
CompactedDBG::filter(): Found 0 unique k-mers
CompactedDBG::filter(): Number of blocks in Bloom filter is 1
GFA_Parser::open(): Wrong GFA header in ~/data/graph_files/genome1.contigs.gfa
CompactedDBG::construct(): Extract approximate unitigs
CompactedDBG::construct(): Closed all input files

CompactedDBG::construct(): Splitting unitigs (1/2)

CompactedDBG::construct(): Splitting unitigs (2/2)
CompactedDBG::construct(): Before split: 0 unitigs
CompactedDBG::construct(): After split (1/1): 0 unitigs
CompactedDBG::construct(): Unitigs split: 0
CompactedDBG::construct(): Unitigs deleted: 0

CompactedDBG::construct(): Joining unitigs
CompactedDBG::construct(): After join: 0 unitigs
CompactedDBG::construct(): Joined 0 unitigs
GFA_Parser::open(): Wrong GFA header in ~/data/graph_files/genome1.contigs.gfa

CompactedDBG::write(): Writing graph to disk

DataStorage::write(): Writing colors to disk

The Bifrost output graph is emty except for the header:
H       VN:Z:1.0        BV:Z:0.2        KL:Z:31 ML:Z:23

The assembly graphs that I'm trying to build the Bifrost graph from have been produced using the SPAdes assembler with the Shovill pipeline and they lack header (line starting with "H" in the gfa). The format is as follows:

S       3107671 TAATAAATATCCTCCGGCATAGCCGGAGGTTTTTCTGATGCGCCTGTAAGGCTCTCTTACCAGCCGCGCCCTAACAGGCGCATACGATCTGACATTTGCATCAAACTTCGTTACTTACGGCCCGTAAA        KC:i:232

These gfa files only contain segment (S), link (L) and path (P) lines, but no header (H).

I did manage to build a Bifrost graph from the assembled contig fasta files.

I also encountered the same error message when trying to update a Bifrost graph with gfa files. I used the following command:
./Bifrost update -t 2 -c -v -r ${DATADIR}/genome10_contigs.gfa -g ${OUTDIR}/Bifrost_graph.gfa -o ${OUTDIR}/updated_graph1

I'm new to Bifrost and thus not sure if I'm using it correctly nor if it's intended to construct a colored compact graph from just a list of gfa files. I would greatly appreciate if you could help me with this issue or provide guidelines on how to correctly use Bifrost. 

Kind regards,
RogerBP

**Comment by GuillaumeHolley** [comment]
Hi :)

Thank you for using Bifrost. As you have mentioned and as Bifrost tells you in its output, your GFA files are missing the header line. My understanding of the [GFA specification](http://gfa-spec.github.io/GFA-spec/GFA1.html) is that the header line is mandatory so Bifrost expects to read one. Unless my interpretation is wrong, GFA files produced by SPAdes or the Shovill pipeline are then not correctly formed.
In any case, this is easily solvable: just add the extra line `H	VN:Z:1.0` at the top of each of your GFA file and Bifrost should run without any problem.

Let me know how it went or if you have any other issues.

Best,
Guillaume

**Comment by Roger-BP** [comment]
Hi Guillaume,

Thanks for the quick response. I've tried that, but for some reason I get a segmentation error:

KmerStream::KmerStream(): Start computing k-mer cardinality estimations
./build_bifrost_gfa.sh: line 34: 16747 Segmentation fault      (core dumped) ./Bifrost build -t 1 -k 31 -c -v -r ${DATADIR}/isolate_graph_list.txt -o ${OUTDIR}/Bifrost_graph1

I don't know where that comes from. Any ideas?

**Comment by GuillaumeHolley** [comment]
Hi Roger,

Unfortunately, I don't know what is going on here. My wild guess is that Bifrost does not like how your GFA files are formed and hence, crashes while trying to read them.
If you would be willing to share your input files, I could try it myself and debug what is the problem. If those are not too big, you can share them here. If they are too big or privacy is an issue, you can also send me a link where I can download them.

**Comment by Roger-BP** [comment]
Hi Guillaume, :)

I've tried with other assemblers (Velvet and Unicycler) and I'm still encountering the same error. I'm starting to think that something must be wrong with my installation even though I don't recall getting any errors/warnings when compiling.

I've uploaded 2 assembly graphs here in case you want to check them:
https://drive.google.com/open?id=1ttnVZpW9aVLOoMP-PQRylH3A4amRG4MM


Thank you for your help. I'll be busy for a few days with other stuff, but I'm definitely coming back to trying to solve this when I get the chance. Looking forward to using Bifrost!

Hugs,
RogerBP

**Comment by GuillaumeHolley** [comment]
Hi Roger,

Thanks for sharing your data, I just downloaded them and I will get on it asap. I don't think your installation has an issue though, its more likely something in the GFA that Bifrost does not handle well.

Guillaume

**Comment by GuillaumeHolley** [comment]
Hi Roger,

Thank you for your patience. I have pushed a new version of Bifrost which hopefully solves your issues. Let me know how it goes.

Guillaume

**Comment by Roger-BP** [comment]
I've tried with the new version and it worked.

Thanks, Guillaume! :)
