### ISSUE TITLE
File checks could be improved

### ISSUE THREAD

**Issue by ar0ch** [pmelsted/bifrost#13]
First off, awesome idea and project.  The Bifrost and BlastFrost papers popped up right when I was in need of this exact functionality.

The file checks in [KmerStream.hpp](https://github.com/pmelsted/bifrost/blob/4995a444d2b4e2962abf88381ada2c5f79c0cb09/src/KmerStream.hpp#L796-L826) and [CompactedDBG.tcc](https://github.com/pmelsted/bifrost/blob/4995a444d2b4e2962abf88381ada2c5f79c0cb09/src/CompactedDBG.tcc#L517=L537) only rely on file suffixes and not actual contents.  This makes sense in the context of the "is this a gz file or not?" check but doesn't necessarily make sense for the other inputs.  For example, many of the database sequence collections (especially from i.e. NCBI/EBI) are distributed as `<dbname>.gz`.  Our lab also, by convention, names text files that contains file paths as `<description>.list` (e.g. neisseria_genomes.list).   

For now I'm using symlinks to make "`<dbname>.fasta.gz`" and "`<list>.txt`", but a nice UX improvement would be extending the fileparser to instead start reading the file and look for `>` and `@` to distinguish fasta and fastq files, and only bail if the inferred format is not followed.

**Comment by GuillaumeHolley** [comment]
Hi there,

Thanks for using Bifrost. I totally agree with you that this suffix checking of the input filenames is bad and definitely not sustainable. It was implemented this way to have something in place quickly but we have been planning for a long time now to do some auto-detection of the input file formats. I am planning a new release of Bifrost for next week and I will include this feature in the release after that. In the meantime, I am keeping this issue open.

**Comment by winni2k** [comment]
Perhaps the [kseq.h](https://github.com/lh3/seqtk/blob/master/kseq.h) header from Heng Li's seqtk might be of use here?

**Comment by ar0ch** [comment]
@GuillaumeHolley  Awesome! 😄  Looking forward to see how this project grows and matures.

**Comment by GuillaumeHolley** [comment]
Hello @ar0ch,

Thank you for your patience. It took some time but finally, commit 5cad28ca33b7eb64a285514fdcc18fe41c5a55e7 adds the automatic detection of input files format. You can now input FASTA/FASTQ/GFA, gzipped or not, as before but filenames or file extensions don't matter anymore.

I'm closing this issue now but feel free to file a new issue if you encounter any problem with that feature.
