### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by tseemann** [pmelsted/bifrost#14]
```
% Bifrost --version 2> /dev/null
Bifrost 1.0

% echo $?
0
```

Thanks - will make conda and brew recipes more robust

**Comment by tseemann** [comment]
Docs say the regular help will show version 
```
displays the command line interface:

Bifrost x.y

Highly parallel construction, indexing and querying of colored and compacted de Bruijn graphs
```
But my output is blank (from 1.0 .tgz)

**Comment by GuillaumeHolley** [comment]
Commit 528b6269d8f01c1a47e69321e000478a83e02cbb

```
% Bifrost --version 2> /dev/null
1.0.3
```

I also added a `--help` subcommand which shows the regular help with the version number.
