### ISSUE TITLE
How to get the unitig/node ID from the query?

### ISSUE THREAD

**Issue by mr-eyes** [pmelsted/bifrost#16]
Hi,
> Thank you for this amazing project.

In the `query` mode. I'm wondering if it's possible to get the `unitig_id` or the `node_id` from the GFA file?

**For example**
If I performed a query by the kmer `GCTCACCGCGCGGTTTT` on the following GFA can I get the `S:10` information from the query? If there's no direct way to get this, I can modify the source code after getting a hint from you.

```txt
H       VN:Z:1.0        ks:i:75
S       10      CTTCCTCGCTCACCGCGCGGTTTTGTTCCCTCTACAAGCTGGCCTGACTCAGGCATGCCTGCTCACGGAACTGCAGTGTGAC      LN:i:82 KC:i:24 km:f:3.0
L       10      +       10033401        +       74M
S       11      CTCCCGGAAGGCTCTGGCCCTTCCTCATCCCAGACGGCAACAAAACCGCGCCGGCTGAGCTCCGCCTCCACGGGAAAGCC        LN:i:80 KC:i:1526       km:f:254.3
L       11      -       12      +       74M
L       11      +       14      +       74M
L       11      +       11738694        +       74M
S       12      CCCGTGGAGGCGGAGCTCAGCCGGCGCGGTTTTGTTGCCGTCTGGGATGAGGAAGGGCCAGAGCCTTCCGGGAGCA    LN:i:76 KC:i:557        km:f:278.5

```

I'll be really glad if this could be possible.
Thank you.

**Comment by GuillaumeHolley** [comment]
Hi @mr-eyes,

Thank you for using Bifrost. The simple answer is no, the query subcommand only returns presence/absence for each query. Returning the Sequence ID from the GFA file could be possible but it would create a very large and messy output file.

**However**, you can absolutely do this, rather easily, with the API. What you are interested in is the function `bool CompactedDBG<U, G>::search()` in file `Search.tcc`. The following lines [here](https://github.com/pmelsted/bifrost/blob/d2524873f56cb656d6b792c7fff80295b88b68e3/src/Search.tcc#L1266) and [here](https://github.com/pmelsted/bifrost/blob/d2524873f56cb656d6b792c7fff80295b88b68e3/src/Search.tcc#L1158) return all `UnitigMap` that are k-mer hits between the queries and the graph. You can parse those and see which k-mers of your queries map on the graph and where. Have a look at the code of `bool CompactedDBG<U, G>::search()` and the doc for manipulating `UnitigMap` (in this case, you "mapped sequence" is a k-mer from a query). One last thing: the Sequence IDs provided in the GFA file are not used internally by the data structure. So in the API, a unitig is only identified by its sequence.

Let me know if this answer your question.

Guillaume

**Comment by mr-eyes** [comment]
Thanks, @GuillaumeHolley for your detailed reply.
I will try out your proposed solution shortly and I will keep you updated here.

Another question could solve the issue if it's less difficult. 
In the colored cDBG, is it possible to change the kmers colors from being the **"reference file name"** to **"the Fasta header"**? So I can easily parse the output TSV.

**Comment by GuillaumeHolley** [comment]
Unfortunately, I have to answer by the negative once again: colors systematically represent the input files. I believe this is a good suggestion of feature though and I will add it on my list of improvements. I cannot guarantee when this feature will be out but it is on the list :)
On the other hand, you can "trick" Bifrost by splitting your input contigs/chromosomes (I assume here that your input are assembled genomes, aren't they?) into different files where each file will have the name of the contig/chromosome. I know it's not ideal but you will obtain the result you are looking for.

**Comment by GuillaumeHolley** [comment]
I'm closing the issue, let me know if you have more questions.

**Comment by mr-eyes** [comment]
Thanks @GuillaumeHolley for your prompt and detailed reply.

Yes, you guessed right. The trick came to my mind but I'm not sure about the efficiency of the I/O reading/writing thousands of files, it's a bit huge experiment.
It'd be really great if this could be added as a feature and I will certainly be happy contributing to its development.

Thank you,
