### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by fishextinction** [pmelsted/bifrost#2]
I'm attempting to use Bifrost and getting errors or incomplete results. I didn't see an example dataset included with the package, so I'll use the 'prasinoviruses' small dataset included in the new SANS package, which is 13 200kb fasta files

If I run Bifrost with default parameters to output a colored graph:
`Bifrost build -r list.txt -o pra -v -c`

I get a segfault after:
> Splitting unitigs (2/2)

If I run a large kmer size:
Bifrost build -r list.txt -o pra_lg -v -c -k 61 -m 59

I get a small text file with 6 lines, fewer than the samples.

I try a kmer size below 31 (likely the way to go with viruses) it just segfaults.

**Comment by GuillaumeHolley** [comment]
Hi there.

Thank you for opening this issue. I don't have access to a computer right now but I will tonight. Fortunately, the output seems to be quite small so I should know what's going on quickly enough. I will let you know what I find out.

Guillaume

**Comment by GuillaumeHolley** [comment]
So I ran Bifrost on my computer with the command lines you gave me and the output is just fine. To be sure it works, I ran it as well with Valgrind in debug mode to check for memory leaks and wrong memory access: everything is all right. Then, to be extra sure it works, a colleague of mine ran Bifrost on the same dataset but a different computer and it also works just fine.

From there, I am not sure what's going on. It is also very peculiar that in your case, it crashes nearly at the end of the graph construction for the default parameters (k=31) but right at the beginning for non-default parameters (k<31) and it works with a suspicious output for k=61.

Here are a few questions that might help me:
- What OS are you using?
- What compiler and which version of it are you using?
- Are you compiling the latest version of Bifrost?
- For the default parameters and k=61, can you copy here the complete output of Bifrost up to the segfault?
- Make sure that when you compile for k>31, you set MAX_KMER_SIZE to a power of 2 value. For example, MAX_KMER_SIZE set to 64 allows you to run Bifrost with k <= 63. Setting this variable to a non-power of 2 value is undefined behavior and will likely crash the program.

**Comment by GuillaumeHolley** [comment]
I am closing the issue for now. Feel free to reopen a new one if you still have problems.
