### ISSUE TITLE
Bifrost query output .tsv merging rows in presence/absence matrix when multithreading

### ISSUE THREAD

**Issue by samhorsfield96** [pmelsted/bifrost#23]
I've encountered a potential issue in the presence/absence matrix .tsv produced by Bifrost query mode. When using multiple threads (>1), I've found some rows in the .tsv are merged with the row above (see attached .tsv files, '_tX' denotes the number of threads used to run query mode). For example, in file 'rep_bifrost_List_graph_t2.tsv', query_name 3429 is merged with the row containing query_name 3236 (see attached image). This does not occur when using only a single thread, and the same rows are not merged when running with different numbers of threads.

![Bifrost_troubleshooting](https://user-images.githubusercontent.com/57448593/83022716-d836f000-a023-11ea-8c10-0c59c24dec53.png)

The command used to generate the attached .tsv files is found below, where X is the number of threads used to run query mode. All files used to generate .tsv files are also attached.

```Bifrost query -g rep_bifrost_List_graph.gfa -q rep_bifrost_List_graph_unitigs.fasta -o rep_bifrost_List_graph_tX -e 1.0 -f rep_bifrost_List_graph.bfg_colors -k 31 -m 23 -t X```

I hope this helps, please let me know if you require any further information.

[troubleshooting.zip](https://github.com/pmelsted/bifrost/files/4688905/troubleshooting.zip)

**Comment by GuillaumeHolley** [comment]
Hi @samhorsfield96,

Thank you for reporting this issue. I believe I have found the issue and I will push a fix for it tonight. I will let you know when it is online.

Guillaume

**Comment by GuillaumeHolley** [comment]
Just pushed the fix, can you let me know if it works on your side?

**Comment by samhorsfield96** [comment]
Hi Guillaume,

I've just tested the fix on the same files and unfortunately it seems the issue is still there (please see attached files). For example, in rep_bifrost_List_graph_t2_new.tsv, pattern_ID 27681 is merged with pattern ID 29773. This was generated using Bifrost v1.0.4.

Sam
[Troubleshooting.zip](https://github.com/pmelsted/bifrost/files/4694236/Troubleshooting.zip)

**Comment by GuillaumeHolley** [comment]
Hi @samhorsfield96,

I will have another look at it this weekend.

Guillaume

**Comment by GuillaumeHolley** [comment]
Hey @samhorsfield96,

Sorry for the delay. I have pushed the fix, could you give it one more try and let me know how it works for you?

Guillaume

**Comment by samhorsfield96** [comment]
Hi @GuillaumeHolley 

Yes, this works perfectly! Many thanks for sorting this issue. Is there a plan to push this fix to the version on bioconda?

Thanks again, Sam

**Comment by GuillaumeHolley** [comment]
We are currently discussing in issue #20 a new bioconda version of Bifrost that would include targeted architecture optimizations. I have no doubt that when it is ready, it will have the latest Bifrost version :)
