### ISSUE TITLE
last file ignored for fofn input?

### ISSUE THREAD

**Issue by ptrebert** [pmelsted/bifrost#27]
Hi,
I have a question regarding the use of a "file of filenames" to supply several read and reference sequence files to Bifrost (build from source `ab43065`). I used text files with two read sets (`-s`) and four reference sequences (`-r`), but when I queried the graph, the resulting tsv had only four columns; one read data set and one reference file was missing. Since in both cases, the respective file was the last one in the file of filenames, it looks like the file is not properly read. If I had to guess, I would assume that this may be caused by a "missing" `\n` after the last line in the fofn.
Best,
Peter

**Comment by ptrebert** [comment]
confirmed: I added a newline at the end of the fofn files, and after rerunning everything, the missing sequences actually show up in the output of the `Bifrost query` command. Would be great if that could be fixed.

**Comment by lrvdijk** [comment]
On any Unix system, files that do not end in a newline are discouraged (and probably don't work properly with many other unix tools too), so may not be a Bifrost bug.

https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert and @lrvdijk,

Sorry for the delay, I am currently in holidays and I will have a look/fix it as soon as I am back (next week). I keep the issue open in the meantime ;)

**Comment by GuillaumeHolley** [comment]
Hey @ptrebert and @lrvdijk ,

As stated above, "it's not a bug: it's a feature" :) Input list files must end with a newline character.
