### ISSUE TITLE
Does Bifrost provide k-mer counts?

### ISSUE THREAD

**Issue by lrvdijk** [pmelsted/bifrost#29]
I see the CompressedCoverage class in the source code, but after reading the code a bit more, it seems to stop counting after it passes the filter (to keep a k-mer).

**Comment by lrvdijk** [comment]
As far as I understand, it has a 2 bit counter which is used to filter low-coverage <2x k-mers. But it doesn't provide full k-mer counts.

**Comment by GuillaumeHolley** [comment]
Hi @lrvdijk,

I'm sorry for the delay, I am currently in holidays and I was expecting to answer all Bifrost related issues/PR when I am back next week.

Your understanding is correct: k-mers only have a 2 bits counter associated with them to filter low coverage k-mers when read are input. It used to be that we were also storing a mean k-mer coverage per unitig (you surely have seen some legacy code for it) but this information was optional and I do not save it anymore to have Bifrost more memory efficient. If k-mer counts are of interest, this can be implemented rather easily with the API.
