### ISSUE TITLE
How can I read the output color file .bfg_colors? 

### ISSUE THREAD

**Issue by XiangLiKyle** [pmelsted/bifrost#3]

**Comment by GuillaumeHolley** [comment]
Hi,

The output color file with extension .bfg_colors is a binary file format which is intended to be used only by Bifrost at the moment (to save your colors on disk and load them again).
If you want to know the colors associated with your k-mers/unitigs, the only option there is at the moment is to use the C++ API to load your graph + colors, iterate over the unitigs of the graph, then iterate over the colors set of each k-mer within the unitigs and write them to a file in the format that you want.

Guillaume

**Comment by ekg** [comment]
I've found that pybind11 is a good way to add a python interface to a C++
API. This might help users who want to work with this file type.

**Comment by GuillaumeHolley** [comment]
Hi,

We actually started a Python API using pybind11 some time ago but there is still a lot of work to do on it. I will update the README when it is ready but since we don't have a release date in mind, I wouldn't expect it anytime soon.

**Comment by GuillaumeHolley** [comment]
I will close this issue as I think the question is answered. Feel free to open another one if you have another question.

**Comment by phiweger** [comment]
@GuillaumeHolley I think the ability to parse color metadata would be very useful. in the absence of a Python API I can parse the graph myself and do stuff w/ it. but the color information is missing for several use cases I imagine. 

would it be possible to give bifrost a flag to write the node: color mapping to eg csv or some non-binary format? BlastFrost can do this (it writes it to the gfa file) so I guess the corresponding code could be more or less copied (yes I could just use BlastFrost, but the overhead of reloading the graph etc. seems like a lot of work to basically get the color info in parseable format).

thanks a lot!
