### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by phiweger** [pmelsted/bifrost#30]
Very great tool!

Have you planned to provide Python bindings of the Bifrost library?

I am asking bc/ I would like to e.g. identify unitigs that contain all colours, and I guess this is trivial using the library, but C++ gets in the way (for many users I think).

Best

**Comment by winni2k** [comment]
If I understand you correctly, then I think [pyfrost](https://github.com/broadinstitute/pyfrost) might be what you are looking for?

**Comment by winni2k** [comment]
See also #10

**Comment by phiweger** [comment]
haha amazing! thanks a lot!
