### ISSUE TITLE
API

### ISSUE THREAD

**Issue by LucasBarbosaRocha** [pmelsted/bifrost#31]
Hello,

In the intro.md we have:

UnitigMap<> um = cdbg.find(km);

`if (um.isEmpty) cout << "Kmer " << kmer_sequence << " was not found" << endl;`
`else {`
`const string unitig = um.referenceUnitigToString();`
`const string strandness = um.strand ? "forward" : "reverse-complement";`
`const size_t position =` um.**pos**;
`}`

But, the pos variable does not exist in the data structure. What should I do to find the position of a k-mer in the graph?

Thanks,
Lucas B. Rocha

**Comment by GuillaumeHolley** [comment]
Hi @LucasBarbosaRocha,

Sorry about that, that's a mistake from my side. The variable you are looking for is not `pos` but `dist`. I will edit the tutorial tonight (and maybe write some more this weekend). In case of doubt or mistake, it is good practice to have a look at the documentation generated by doxygen since it is automatically generated from the code itself.

I will close the issue after editing the tutorial. Thank you for reporting this issue.

Guillaume

**Comment by LucasBarbosaRocha** [comment]
Hi Guillaume,
Thanks for your answer.

I would like to ask another question. Given a sequence and a Bruijn graph.
I'm looking for a tool that builds the graph of bruijn and that gives me back the position of the vertex that the substring of my sequence matched. In the following way:

Sequence s = AACGTT
And a part of the De Bruijn Graph: ACG -> CGT -> GTT 
And the tools gives me the position of the node, for example, CGT for my substring CGT from AA**CGT**T.

I saw that the Query function returns only 1 or 0 to be present or not. So I searched the API, but I didn't find how to return the position of the k-mer. 

If possible, what is your suggestion to use the API to do what I need? 
A good way is using unitig's getSuccessors() function?

Thank you so much Guillaume,
Lucas B. Rocha

**Comment by GuillaumeHolley** [comment]
Hi Lucas,

I think what you are looking for is the function `searchSequence()`. According to the doc `Performs exact and/or inexact search of the k-mers of a sequence query in the Compacted de Bruijn graph.` Returns `a vector of pair<size_t, UnitigMap<U, G>> objects. Each such pair has two elements: the position of the k-mer match in sequence seq and the corresponding k-mer match in the graph. Note that no information is given on whether the match is exact or inexact, nor on what edit operation makes the match to be inexact or at what position the edit operation takes place.`

Guillaume

**Comment by LucasBarbosaRocha** [comment]
Hi Guillaume,

Interesting. This function seems to be exactly what I need. I am studying your tool at the moment. I believe that the API will suit me perfectly, I hope.

Thank you so much Guillaume,
Lucas B. Rocha

**Comment by GuillaumeHolley** [comment]
Cool :) Let me know if you have more questions!

Guillaume
