### ISSUE TITLE
GFA output: DA field meaning

### ISSUE THREAD

**Issue by tillbaar** [pmelsted/bifrost#37]
In the GFA output, all segments carry an optional field with the tag DA of type Z (printable string incl. whitespace). What is the meaning of this field?
At least in the output files I generated so far, this field always contained an integer >0.

I hope I didn't just overlook the explanation somewhere in the documentation.
Also, I am blown away by how fast Bifrost is. Awesome work!

Thanks, Till

**Comment by GuillaumeHolley** [comment]
Hi @tillbaar,

The optional field "DA" stands for "Data Access": It is used by Bifrost to associate unitigs to their color classes when reading a colored de Bruijn from disk. Hence, it is only output if a colored de Bruijn graph is created.

Thank you for your kind words, let me know if you have any questions or suggestions about Bifrost.

Guillaume
