### ISSUE TITLE
[feature request] dumping color file into parsable format

### ISSUE THREAD

**Issue by damiankao** [pmelsted/bifrost#50]
It would be great if we can dump the color file into a text format or something easier to parse so we can analyze the graph.

**Comment by cgroza** [comment]
This would be useful for creating phylogenies based on k-mer sharing between colours using metrics like Jaccard distance.

**Comment by cgroza** [comment]
The right solution to this is to use the Bifrost API.
I have made an attempt here, maybe it is useful to others:
https://github.com/cgroza/bifrost_jaccard

**Comment by GuillaumeHolley** [comment]
Hi everyone,

@cgroza Thank you for your implementation!

There is now another very simple solution to do this:

1. Make a FASTA file of each k-mer in the segments of the GFA file. Assuming k=31:
```
zcat mygraph.gfa.gz | awk 'BEGIN {K=31} {if ($1=="S"){LEN_KM_UNITIG=length($3)-K+1; for (i=1; i<=LEN_KM_UNITIG; i+=1){print ">" $2 "_" i "\n" substr($3,i,K)}}}' > mygraph.kmers.fasta
```
Every record in the generated FASTA file has the form `>x_y` where `x` is the ID of the unitig the k-mer is from in the GFA and `y` is the position of the k-mer within that unitig in the GFA.

2. Query the colored graph using the previously generated GFA
```
Bifrost query -v -t 16 -e 1.0 -g mygraph.gfa.gz -C mygraph.bfg_colors -q mygraph.kmers.fasta -o mygraph.colors
```
The output file will be `mygraph.colors.tsv` which is a matrix (k-mers x colors). The intersection of a row (k-mer) and column (color) contains a binary value indicating whether the corresponding k-mer has the corresponding color (1) or not (0).

Given that Bifrost graphs are now fully indexed (.bfi file output alongside the gfa) and are very fast to load in memory, this solution should take no time.
