### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by LucasBarbosaRocha** [pmelsted/bifrost#52]
Hi Friends,

Could you tell me how I fix this warning?

warning: ‘BlockedBloomFilter’ has a field ‘BlockedBloomFilter::fast_div_’ whose type uses the anonymous namespace [-Wsubobject-linkage]
 class BlockedBloomFilter {
 
 Thanks,
 Lucas B. Rocha

**Comment by GuillaumeHolley** [comment]
Hi @LucasBarbosaRocha 

You cannot but I can, I probably need to add a namespace for it or something like that. It's not super nice to see that warning when you compile Bifrost but it is an important warning.

I'll let you know as soon as I have fixed it.

**Comment by jessicalumian** [comment]
Hi, just wondering if this been fixed? If not, will it affect the bifrost functionality? I am getting the same warning after running 

```
sudo apt-get install build-essential cmake zlib1g-dev

git clone https://github.com/pmelsted/bifrost.git
cd bifrost && mkdir build && cd build
cmake ..
make
make install
```

but it seems like the install was successful. thanks!

**Comment by GuillaumeHolley** [comment]
@jessicalumian The warning has not (yet) been fixed but it won't affect bifrost functionality in any way.
