### ISSUE TITLE
bad alloc in v1.0.5 and latest master

### ISSUE THREAD

**Issue by ptrebert** [pmelsted/bifrost#54]
Hi,

I get the below error for both the v1.0.5 installed from Conda (with k=31) and the latest master build (with k=63) for the Bifrost `build --colors` command:

```bash
KmerStream::KmerStream(): Start computing k-mer cardinality estimations
CompactedDBG::build(): Estimated number of k-mers occurring at least once: 119170197639
CompactedDBG::build(): Estimated number of minimizer occurring at least once: 25150968762
CompactedDBG::build(): Estimated number of k-mers occurring twice or more: 24926987045
CompactedDBG::build(): Estimated number of minimizers occurring twice or more: 5164277853
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

The input is a bunch of read files (mixed gzipped fastq and fasta). I tested the same command (using the latest master build) with two small fasta files, and that works. Could that be a simple issue with the input reads (similar to #21)? Any suggestion what to look for?

Thanks!

**Comment by GuillaumeHolley** [comment]
Hi @ptrebert,

I am closing for now but feel free to reopen if this is still an issue.

Guillaume
