### ISSUE TITLE
Houston, I have a problem²

### ISSUE THREAD

**Issue by LucasBarbosaRocha** [pmelsted/bifrost#56]
Guillaume, I have a important question...

in July I was using Bifrost and I created a graph with 3 <= k <= 31 and it worked normally.

This week I did git the latest version of bifrost and I can only add sequences for 29 <= k <= 31... To check this question, I put a print inside the first for of the **bool function CompactedDBG<U, G> ::add(const string&seq, const bool verbose){...}** and it's with an infinite loop.

I took an old version of the bifrost I was using and was able to use it for all 3 <= k <= 31 and add the sequences.

Could you tell me what this question is about?

Thanks,
Lucas B. Rocha

**Comment by GuillaumeHolley** [comment]
Hi @LucasBarbosaRocha,

Closing the issue for now but feel free to reopen if this is still an issue.

Guillaume
