### ISSUE TITLE
The result unitig of findunitig of compactedDBG doesn't contain the kmer sometimes

### ISSUE THREAD

**Issue by XiangLiKyle** [pmelsted/bifrost#6]
I check whether string from referenceUnitigToString() contains the kmer used to findUnitig and many of them are false.

**Comment by GuillaumeHolley** [comment]
I find it quite surprising and unlikely that CompactedDBG::findUnitig() returns false positives. It is a method a use quite extensively during the graph construction and the graphs I obtained so far are correct. I am also using it another project using Bifrost and I didn't notice any false positives in my results. On the other hand, no code is ever mistake-free so I cannot discard the possibility of a bug.

When you check for the k-mers in the string returned by UnitigMap::referenceUnitigToString(), do you also check for the k-mers in the reverse-complement of that string?  UnitigMap::strand = false means that the k-mer / substring you are looking for is present on the reverse-complement of that string. Or you can use UnitigMap::mappedSequenceToString() which was designed specifically for that purpose: returning the string of the mapped sub-unitig (taking into account that the mapped subsequence can be on the reverse-complement of the unitig).

If you checked for the reverse-complement and you still have false positives, it is probably best if you can send me a minimal working example for me to reproduce the issue on my side (input graph. input query and minimal piece of code).

**Comment by XiangLiKyle** [comment]
> I find it quite surprising and unlikely that `CompactedDBG::findUnitig()` returns false positives. It is a method a use quite extensively during the graph construction and the graphs I obtained so far are correct. I am also using it another project using Bifrost and I didn't notice any false positives in my results. On the other hand, no code is ever mistake-free so I cannot discard the possibility of a bug.
> 
> When you check for the k-mers in the string returned by `UnitigMap::referenceUnitigToString()`, do you also check for the k-mers in the reverse-complement of that string? `UnitigMap::strand == false` means that the k-mer / substring you are looking for is present on the reverse-complement of that string. Or you can use `UnitigMap::mappedSequenceToString()` which was designed specifically for that purpose: returning the string of the mapped sub-unitig (taking into account that the mapped subsequence can be on the reverse-complement of the unitig).
> 
> If you checked for the reverse-complement and you still have false positives, it is probably best to send me a minimal working example such that I can reproduce the issue on my side (input graph. input query and minimal piece of code).

I believe it is because of the reverse-complement, thank you very much for your patience, I am sorry for my negligence.

**Comment by GuillaumeHolley** [comment]
No worries ;) I am closing the issue.
