### ISSUE TITLE
This soft can assembly mtDNA ?

### ISSUE THREAD

**Issue by deyuanyang** [pmelsted/bifrost#69]
Hi,
Considering the fast assembly of this software, when I provide the mitochondrial genome as "-s", the mitochondrial contigs can be quickly assembled?

Deyuan

**Comment by GuillaumeHolley** [comment]
Hi @deyuanyang,

Bifrost does not perform assembly, it creates (colored) compacted de Bruijn graphs (in which vertices are unitigs and not contigs) out of input reads/contigs sets.

Guillaume
