### ISSUE TITLE
SNP calling on Bifrost output

### ISSUE THREAD

**Issue by JensUweUlrich** [pmelsted/bifrost#72]
Hi,

I just have a question regarding post-processing of the Bifrost output. Do you know any tool that is capable of SNP calling/genotyping directly on a coloured dBG as produced by Bifrost?

Best,
Jens

**Comment by GuillaumeHolley** [comment]
Hi @JensUweUlrich,

Not exactly what you are asking for but related work: https://github.com/samhorsfield96/ggCaller
Otherwise, I am not aware of any variant caller/genotyper working directly on a colored dBG as produced by Bifrost.

Guillaume

**Comment by JensUweUlrich** [comment]
Thanks for you quick response!
