### ISSUE TITLE
Release 0.1.tgz has no CMake files?

### ISSUE THREAD

**Issue by tseemann** [pmelsted/bifrost#8]
Unable to build from release tarball because missing cmake data as per install instructions.

Seems the README in the tgz says to just use `make` ?

**Comment by GuillaumeHolley** [comment]
I'm a little bit confused here. I didn't tag any release 0.1. Did you get that tarball from this repo or from somewhere else?

**Comment by GuillaumeHolley** [comment]
My bad, there was indeed a release 0.1 dating from 7 years ago, back in the days where Bifrost had a different name and was a different idea. I just removed that release tarball but I am planning a release next week for a bioconda package.
