### ISSUE TITLE
writing graph index hangs in 1.3.0 upward

### ISSUE THREAD

**Issue by vpbrendel** [pmelsted/bifrost#80]
Great program. Thanks. I was testing a different program (https://github.com/tischulz1/plast) that makes use of bifrost and ended up with an odd error. Could you please take a look?

Here is my odd sequence:
>oddseq
GAATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATTG

Here is how I use it:
mkdir fa
cd fa
wget 'ftp://hgdownload.cse.ucsc.edu/goldenPath/eboVir3/bigZips/160sequences.tar.gz'
tar xzf *.gz
\rm *.gz
cd ..

ls fa | sed -e "s#^#fa/#" > slst

../bifrost-1.2.1/build/src/Bifrost build -o mygfa-1.2.1 -r slst -t 10 -n -v >& err-1.2.1
../bifrost-1.3.0/build/src/Bifrost build -o mygfa-1.3.0 -r slst -t 10 -n -v >& err-1.3.0

cat slst | sed -e '$a gnm.fa' > slstF
../bifrost-1.2.1/build/src/Bifrost build -o mygfa-1.2.1F -r slstF -t 10 -n -v >& err-1.2.1F
../bifrost-1.3.0/build/src/Bifrost build -o mygfa-1.3.0F -r slstF -t 10 -n -v >& err-1.3.0F

Outcome: The plast example (ebola sequences) works fine with 1.2.1 and 1.3.0. Then I add my odd sequence to the fa directory. 1.2.1 is still happy. But 1.3.0 hangs on writing the index.

Multiple testing of similar cases on Fedora 39 Linux. I think this happens in IO.tcc, but you will know better.
Thanks, Volker

**Comment by GuillaumeHolley** [comment]
README for that branch should be fairly up to date now.

**Comment by GuillaumeHolley** [comment]
v1.3.5 has been released, I am confident it solves your issue. I am closing this issue but feel free to reopen if you encounter additional problems.

Guillaume

**Comment by vpbrendel** [comment]
Thanks Guillaume. I confirm that the current version works as intended.
Volker
