### ISSUE TITLE
Bifrost update does not work, complains about the number of threads

### ISSUE THREAD

**Issue by marade** [pmelsted/bifrost#9]
$ Bifrost update -t 4 -o newgraph -r mygenome.fa -g mygraph.gfa
KmerStream::KmerStream(): Number of threads cannot be less than or equal to 0

$ Bifrost update -o newgraph -r mygenome.fa -g mygraph.gfa
KmerStream::KmerStream(): Number of threads cannot be less than or equal to 0

**Comment by GuillaumeHolley** [comment]
Sorry for the inconvenience. I just pushed a new release, could you try it out and let me know if it works?

**Comment by marade** [comment]
Yes, the issue appears to be solved. Thanks for the rapid response.

**Comment by GuillaumeHolley** [comment]
You're welcome. Don't hesitate to let me know if you encounter other issues.

**Comment by GuillaumeHolley** [comment]
You might want to re-clone & re-install Bifrost, sorry about that. I forgot to set back the default k-mer size for compilation in the CMake file. It means that the version you have will likely use more memory than needed (although the results will be the same). The new release has the right k-mer size set by default.

**Comment by marade** [comment]
Okay, thanks for letting me know.
